exec --no-startup-id dex --autostart

exec swayidle \
    timeout 300 "$lock" \
    timeout 600 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"'

exec scream -u -i virbr0 -o jack
