font pango:DejaVu Sans Mono 8

# Wallpaper
output * bg $bg $bg_scale

# Scale
# output * scale 1.25

for_window [class=".*"] border pixel

gaps inner 5
gaps outer 3

# Waydroid
for_window [app_id="Waydroid"] fullscreen enable
for_window [app_id="^waydroid.*"] fullscreen enable

client.focused		#d18362 #d18362 #ffffff #2e9ef4 #d18362
client.unfocused	#000000 #000000 #ffffff #292d2e #222222

# Bar
bar {
	position top
	status_command i3status

	colors {
		background #000000
		separator #000000
		focused_workspace #d18362 #d18362 #ffffff
		inactive_workspace #000000 #000000 #ffffff
	}
}
