font pango:DejaVu Sans Mono 8

# Wallpaper
output * bg $bg $bg_scale

# Scale
# output * scale 1.25

for_window [class=".*"] border pixel

#gaps inner 0
#gaps outer 3

# Waydroid
#for_window [app_id="Waydroid"] fullscreen enable
#for_window [app_id="^waydroid\..*"] fullscreen enable

client.focused		#887788aa #887788aa #ffffff #ffeeff #887788
client.unfocused	#000000aa #000000aa #ffffff #292d2e #222222
client.focused_inactive	#444444aa #444444aa #ffffff #292d2e #222222

# Bar
bar {
	position bottom
	status_command i3status

	colors {
		background #000000aa
		separator #000000
		focused_workspace #ffffffaa #ffffffaa #000000
		inactive_workspace #000000aa #000000aa #ffffff
	}
}
