font pango:DejaVu Sans Mono 8

# Wallpaper
output * bg $bg $bg_scale

# Scale
# output * scale 1.25

for_window [class=".*"] border pixel

#gaps inner 0
#gaps outer 3

# Waydroid
for_window [app_id="Waydroid"] fullscreen enable
for_window [app_id="^waydroid.*"] fullscreen enable

client.focused		#887788 #887788 #ffffff #2e9ef4 #887788
client.unfocused	#000000 #000000 #ffffff #292d2e #222222

# Bar
bar {
	position bottom
	status_command i3status

	colors {
		background #00000000
		separator #000000
		focused_workspace #ffffffaa #ffffffaa #000000
		inactive_workspace #00000011 #00000011 #ffffff
	}
}
